version: '3.8'

services:
  mongo: 
    image: mongo
    ports:
      - 27017:27017  # enables connecting locally via psql

  backend:
    build: .
    depends_on:
      - mongo
    ports:
      - 5000:5000
      - 9229:9229  # debugger port
    volumes:
      - .:/usr/src/express-app 
      - /usr/src/express-app/node_modules # not mapping or interact with local machine
    command: npm run start:docker # overriding 'CMD' command line of the docker file
    environment:
      PORT: 5000
      MONGO_CONNECTION_STR: mongodb+srv://localhost/ecommerce_express_dev

      